from dataclasses import dataclass
from typing import Optional, List

from scipy.stats import norm


@dataclass
class Descriptor:
    """A dataclass for a string that describes the sensation of listening to a song.

    Attributes:
        - `descriptor`: The string that describes the sensation of listening to a song.
        - `tempo_prob_dist`: Since some descriptions are more appropriate (likely to be used)
          for certain tempos, this attribute is a conditional probability distribution
          of tempos given the presence of this descriptor.
        - `swing_prob`: Since some descriptions are more appropriate (likely to be used) for
          songs with swing (or played as a shuffle), this attribute is the conditional
          probability of the song being swung/a shuffle given the presence of this
          descriptor.
        - `affinity`: A multiplier to compound the probability of this descriptor being
          selected.
    """

    text: str
    tempo_prob_dist: Optional[norm]
    swing_prob: Optional[float]
    affinity: int


SINGLE_WORD: List[Descriptor] = [
    Descriptor(text="jaunty", tempo_prob_dist=norm(loc=120, scale=10), swing_prob=0.6, affinity=1),
    Descriptor(text="anthemic", tempo_prob_dist=norm(loc=92, scale=10), swing_prob=0.5, affinity=1),
    Descriptor(text="reflective", tempo_prob_dist=norm(loc=80, scale=10), swing_prob=0.2, affinity=1),
    Descriptor(text="groovy", tempo_prob_dist=norm(loc=100, scale=23), swing_prob=0.35, affinity=2),
    Descriptor(text="easygoing", tempo_prob_dist=norm(loc=90, scale=22), swing_prob=0.45, affinity=2),
    Descriptor(text="upbeat", tempo_prob_dist=norm(loc=110, scale=25), swing_prob=0.5, affinity=1),
    Descriptor(text="bouncy", tempo_prob_dist=norm(loc=118, scale=13), swing_prob=0.55, affinity=1),
    Descriptor(text="driving", tempo_prob_dist=norm(loc=125, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="rhythmic", tempo_prob_dist=norm(loc=120, scale=40), swing_prob=0.1, affinity=1),
    Descriptor(text="pulsing", tempo_prob_dist=norm(loc=134, scale=12), swing_prob=0.3, affinity=1),
    Descriptor(text="lively", tempo_prob_dist=norm(loc=115, scale=10), swing_prob=0.1, affinity=1),
    Descriptor(text="athletic", tempo_prob_dist=norm(loc=155, scale=30), swing_prob=0.4, affinity=1),
    Descriptor(text="syncopated", tempo_prob_dist=norm(loc=115, scale=30), swing_prob=0.0, affinity=2),
    Descriptor(text="frenetic", tempo_prob_dist=norm(loc=140, scale=30), swing_prob=0.0, affinity=2),
    Descriptor(text="calm", tempo_prob_dist=norm(loc=78, scale=12), swing_prob=0.05, affinity=1),
    Descriptor(text="mellow", tempo_prob_dist=norm(loc=82, scale=10), swing_prob=0.1, affinity=1),
    Descriptor(text="steady", tempo_prob_dist=norm(loc=104, scale=15), swing_prob=0.5, affinity=1),
    Descriptor(text="energetic", tempo_prob_dist=norm(loc=128, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="relaxed", tempo_prob_dist=norm(loc=81, scale=10), swing_prob=0.3, affinity=1),
    Descriptor(text="brisk", tempo_prob_dist=norm(loc=128, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="leisurely", tempo_prob_dist=norm(loc=93, scale=8), swing_prob=0.5, affinity=1),
    Descriptor(text="spirited", tempo_prob_dist=norm(loc=130, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="convolving", tempo_prob_dist=norm(loc=110, scale=25), swing_prob=0.1, affinity=1),
    Descriptor(text="breezy", tempo_prob_dist=norm(loc=150, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="deliberate", tempo_prob_dist=norm(loc=96, scale=10), swing_prob=0.5, affinity=1),
    Descriptor(text="hasty", tempo_prob_dist=norm(loc=150, scale=18), swing_prob=0.4, affinity=1),
    Descriptor(text="majestic", tempo_prob_dist=norm(loc=82, scale=12), swing_prob=0.5, affinity=1),
    Descriptor(text="choppy", tempo_prob_dist=norm(loc=120, scale=40), swing_prob=0.15, affinity=1),
    Descriptor(text="pounding", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.15, affinity=1),
    Descriptor(text="bustling", tempo_prob_dist=norm(loc=165, scale=10), swing_prob=0.5, affinity=2),
    Descriptor(text="sprightly", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="electric", tempo_prob_dist=norm(loc=123, scale=15), swing_prob=0.2, affinity=1),
    Descriptor(text="unwavering", tempo_prob_dist=norm(loc=116, scale=37), swing_prob=0.4, affinity=1),
]


FROM_REVIEWS: List[Descriptor] = [
    Descriptor(text="a meat-and-potatoes thang", tempo_prob_dist=norm(loc=110, scale=20), swing_prob=0.2, affinity=1),
    Descriptor(text="bruising drum work squares off against lightning-like solos", tempo_prob_dist=norm(loc=140, scale=30), swing_prob=0.05, affinity=1),
    Descriptor(text="leaves a peaceful imprint", tempo_prob_dist=norm(loc=70, scale=15), swing_prob=0.1, affinity=1),
    Descriptor(text="advice to loosen up and take risks", tempo_prob_dist=norm(loc=85, scale=30), swing_prob=0.3, affinity=1),
    Descriptor(text="serene, plaintive quality of voice doing the heavy lifting", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="rich and delirious in almost every flutter", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="smarmy schlock rock", tempo_prob_dist=norm(loc=112, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="a f****** beautiful parade", tempo_prob_dist=norm(loc=112, scale=30), swing_prob=0.3, affinity=1),
    Descriptor(text="understated yacht-rocking", tempo_prob_dist=norm(loc=110, scale=20), swing_prob=0.4, affinity=1),
    Descriptor(text="struts at a parade pace", tempo_prob_dist=norm(loc=110, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="felt like a giant hug", tempo_prob_dist=norm(loc=112, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="giving his wayward beats a purposeful attitude", tempo_prob_dist=norm(loc=115, scale=30), swing_prob=0.55, affinity=1),
    Descriptor(text="a slowly cascading chorus that tugs at your heartstrings", tempo_prob_dist=norm(loc=90, scale=13), swing_prob=0.5, affinity=1),
    Descriptor(text="elastic sound with wry lightheartedness", tempo_prob_dist=norm(loc=118, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="a landmark album of 70s funk", tempo_prob_dist=norm(loc=110, scale=20), swing_prob=0.08, affinity=1),
    Descriptor(text="giving it all equal space to shine", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="a touch of self-absorbed fantasy", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="an odd, malfunctioning gimmick", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="swimming through organic muck to reach your ears", tempo_prob_dist=norm(loc=105, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="weightlessly low-key glossy disco", tempo_prob_dist=norm(loc=120, scale=8), swing_prob=0.03, affinity=1),
    Descriptor(text="feels like a thousand little stipples of percussion", tempo_prob_dist=None, swing_prob=0.05, affinity=1),
    Descriptor(text="hit upon a revelation", tempo_prob_dist=None, swing_prob=0.5, affinity=3),
    Descriptor(text="wields a plush comedown", tempo_prob_dist=norm(loc=104, scale=25), swing_prob=0.3, affinity=1),
    Descriptor(text="peculiar mixture of surprise and inevitability", tempo_prob_dist=None, swing_prob=0.5, affinity=4),
    Descriptor(text="fully embraces the cheddar pleasures", tempo_prob_dist=None, swing_prob=0.55, affinity=1),
    Descriptor(text="a warm, inviting, and intimate affair", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="ever-increasing levels of opportunity", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="syncopated, clacking bass", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.1, affinity=1),
    Descriptor(text="razor wit", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="loud nouns painting vivid pictures", tempo_prob_dist=None, swing_prob=0.5, affinity=6),
    Descriptor(text="the consequences of getting in the mood", tempo_prob_dist=None, swing_prob=0.25, affinity=9),
    Descriptor(text="a kind of sonic comfort food", tempo_prob_dist=None, swing_prob=0.47, affinity=6),
    Descriptor(text="juddering squelches", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="a haunting ode to everyday American pain", tempo_prob_dist=norm(loc=70, scale=15), swing_prob=0.1, affinity=1),
    Descriptor(text="real Gorillaz vibe", tempo_prob_dist=norm(loc=108, scale=30), swing_prob=0.04, affinity=1),
    Descriptor(text="connects art and ideas from different eras into a kind of ecstatic worldview", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="they've got to convince themselves of their cool", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="makes the song feel plump at the edges and thin in the middle", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="induces nostalgia, revulsion, historical reconsideration", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="swoop as well as it floats", tempo_prob_dist=None, swing_prob=0.5, affinity=4),
    Descriptor(text="anguished and overcooked", tempo_prob_dist=None, swing_prob=0.5, affinity=3),
    Descriptor(text="coated in molasses", tempo_prob_dist=norm(loc=92, scale=10), swing_prob=0.63, affinity=2),
    Descriptor(text="manipulated voice to an intoxicating effect", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="lightly viscous", tempo_prob_dist=norm(loc=106, scale=18), swing_prob=0.52, affinity=1),
    Descriptor(text="distinctly casual", tempo_prob_dist=None, swing_prob=0.5, affinity=6),
    Descriptor(text="elated melody that feels lifted from a forgotten video game soundtrack", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="slicing disco strings and a tricky chorus melody", tempo_prob_dist=norm(loc=115, scale=13), swing_prob=0.2, affinity=3),
    Descriptor(text="eccentric angles", tempo_prob_dist=norm(loc=105, scale=35), swing_prob=0.5, affinity=2),
    Descriptor(text="noodly", tempo_prob_dist=norm(loc=105, scale=30), swing_prob=0.3, affinity=1),
    Descriptor(text="fantasy of the garden and innocence", tempo_prob_dist=None, swing_prob=0.5, affinity=2),
    Descriptor(text="hooks onto an upswell of emotion, animated with byzantine crashes and buoyant garnishes", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="nurtures eccentricities leading to an arrangement full of colorful moments", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="a beautifully understated but addictive hymn", tempo_prob_dist=None, swing_prob=0.5, affinity=4),
    Descriptor(text="musical gags", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.5, affinity=1),
    Descriptor(text="like your favorite pair of jeans", tempo_prob_dist=norm(loc=110, scale=30), swing_prob=0.45, affinity=2),
    Descriptor(text="simultaneously thick and husky", tempo_prob_dist=norm(loc=87, scale=15), swing_prob=0.4, affinity=1),
    Descriptor(text="an ocean of private lives observed from celestial height", tempo_prob_dist=None, swing_prob=0.3, affinity=2),
    Descriptor(text="an especially liquid sway", tempo_prob_dist=norm(loc=90, scale=15), swing_prob=0.35, affinity=3),
    Descriptor(text="right up my alley (that alley is a dimly-lit space behind a record store in Pomona)", tempo_prob_dist=norm(loc=110, scale=19), swing_prob=0.32, affinity=1),
    Descriptor(text="reflecting on the hard-partying summer", tempo_prob_dist=norm(loc=130, scale=25), swing_prob=0.2, affinity=1),
    Descriptor(text="sound not of one person thinking it through but two people hashing it out", tempo_prob_dist=norm(loc=115, scale=20), swing_prob=0.35, affinity=1),
    Descriptor(text="crack your heart in two", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="egregiously hangs on the bandwagon", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="a puzzling ride", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="biting off that last syllable sharply enough to force the rhyme", tempo_prob_dist=None, swing_prob=0.1, affinity=1),
    Descriptor(text="an enchanting rasp that sandpapers some of the gloss off", tempo_prob_dist=norm(loc=95, scale=15), swing_prob=0.5, affinity=1),
    Descriptor(text="quickly tuned out in favor of quiet beauty", tempo_prob_dist=norm(loc=70, scale=10), swing_prob=0.2, affinity=1),
    Descriptor(text="dancing the listener into the ether", tempo_prob_dist=norm(loc=125, scale=19), swing_prob=0.4, affinity=2),
    Descriptor(text="usher you into a brighter future", tempo_prob_dist=norm(loc=95, scale=20), swing_prob=0.07, affinity=2),
    Descriptor(text="garnished with music-nerd excitement", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="brashness is a tonic", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.3, affinity=1),
    Descriptor(text="austere gestures and a sense of space", tempo_prob_dist=norm(loc=75, scale=15), swing_prob=0.2, affinity=1),
    Descriptor(text="sarcastic nursery rhyme flow", tempo_prob_dist=norm(loc=100, scale=20), swing_prob=0.4, affinity=1),
    Descriptor(text="fantastically druggy and deliciously bass-bombed", tempo_prob_dist=norm(loc=110, scale=25), swing_prob=0.5, affinity=1),
    Descriptor(text="song of contentment sung by agitated people", tempo_prob_dist=norm(loc=95, scale=30), swing_prob=0.3, affinity=1),
    Descriptor(text="amorphous signature sound", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="awkward blurt of a reference to Kareem Abdul-Jabbar", tempo_prob_dist=None, swing_prob=0.2, affinity=1),
    Descriptor(text="off-kilter demeanor", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="celebrating many cultures", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="party rhythms to deadpan poetry", tempo_prob_dist=norm(loc=124, scale=18), swing_prob=0.5, affinity=1),
    Descriptor(text="knocks like a heartbeat", tempo_prob_dist=norm(loc=93, scale=13), swing_prob=0.4, affinity=1),
    Descriptor(text="charming, relatively lighthearted", tempo_prob_dist=norm(loc=113, scale=25), swing_prob=0.4, affinity=1),
    Descriptor(text="a bunch of Brazilian hippies having a blast.", tempo_prob_dist=norm(loc=130, scale=25), swing_prob=0.01, affinity=1),
    Descriptor(text="voice bend into a rapturous coo", tempo_prob_dist=None, swing_prob=0.3, affinity=8),
    Descriptor(text="good-time vibes of a few guys jamming in the sea breeze", tempo_prob_dist=norm(loc=103, scale=26), swing_prob=0.4, affinity=1),
    Descriptor(text="sweet, almost fumbling, open-heartedness", tempo_prob_dist=None, swing_prob=0.1, affinity=3),
    Descriptor(text="violent gothy piece of flamenco", tempo_prob_dist=norm(loc=110, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="rambles back and forth", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="strange, counterintuitive progressions", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="ascending like stadium entrance music", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.2, affinity=1),
    Descriptor(text="what the spirit might endure when the body expires", tempo_prob_dist=None, swing_prob=0.2, affinity=1),
    Descriptor(text="striking hits bobbed among a stew of Motown and psych", tempo_prob_dist=norm(loc=109, scale=25), swing_prob=0.5, affinity=2),
    Descriptor(text="breezes by on gentle guitars", tempo_prob_dist=norm(loc=94, scale=20), swing_prob=0.3, affinity=1),
    Descriptor(text="robust and sleepy at the same time", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="sweet melodies with a light touch", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="feels like you're caught tumble drying with how the rhythm continually cascades", tempo_prob_dist=norm(loc=127, scale=24), swing_prob=0.1, affinity=1),
    Descriptor(text="the vibe does the heavy lifting", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="feels like a gesture of trust", tempo_prob_dist=None, swing_prob=0.23, affinity=1),
    Descriptor(text="bittersweet note to end on", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="a kaleidoscopic mirage", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="conjures '90s nostalgia", tempo_prob_dist=None, swing_prob=0.43, affinity=1),
    Descriptor(text="semi-popular and sincerely idiosyncratic", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="feather-light touches", tempo_prob_dist=None, swing_prob=0.48, affinity=1),
    Descriptor(text="evade pop without skimping on its sensibility", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="light, whimpering vocals", tempo_prob_dist=None, swing_prob=0.3, affinity=2),
    Descriptor(text="would f*** you up if you heard it for the first time", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="elements chase one another around a palindrome of a riff", tempo_prob_dist=norm(loc=140, scale=20), swing_prob=0.1, affinity=1),
    Descriptor(text="frenetic, suspended animation", tempo_prob_dist=norm(loc=140, scale=30), swing_prob=0.2, affinity=1),
    Descriptor(text="yearning for bigger stages, sweeping statements, limitless horizons", tempo_prob_dist=None, swing_prob=0.39, affinity=1),
    Descriptor(text="more digestible than Dirty Projectors, more exciting than Grizzly Bear", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="sticks out like a rejected kidney", tempo_prob_dist=None, swing_prob=0.2, affinity=2),
    Descriptor(text="going over the top here is just part of the package", tempo_prob_dist=norm(loc=130, scale=30), swing_prob=0.4, affinity=4),
    Descriptor(text="charging squelch-fest", tempo_prob_dist=norm(loc=140, scale=30), swing_prob=0.5, affinity=1),
    Descriptor(text="chunky, clumsy riff", tempo_prob_dist=None, swing_prob=0.12, affinity=2),
    Descriptor(text="leaning into the rush of romance and friendship", tempo_prob_dist=norm(loc=100, scale=20), swing_prob=0.4, affinity=3),
    Descriptor(text="oozing disdain", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="contradictions, passions, and superficialities", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="dissection of a myth", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="transition from freezing on the dancefloor to embracing warmth and movement", tempo_prob_dist=norm(loc=115, scale=25), swing_prob=0.5, affinity=1),
    Descriptor(text="utter warehouse madness", tempo_prob_dist=norm(loc=140, scale=30), swing_prob=0.6, affinity=1),
    Descriptor(text="singing like they're measuring the distance to a future", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="instantly collapsing the illusion and thrusting us back into the absurd world around us", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="collective triumph", tempo_prob_dist=None, swing_prob=0.4, affinity=6),
    Descriptor(text="themes of spring, rebirth, shedding of old skin, and reclamation of light", tempo_prob_dist=None, swing_prob=0.4, affinity=5),
    Descriptor(text="a welcome jolt", tempo_prob_dist=norm(loc=130, scale=20), swing_prob=0.3, affinity=3),
    Descriptor(text="pinches of Brainiac moments", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="a sense of wrongness, a screw-faced delight at things gone awry", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="arrives as lazily and beautifully as crashing waves", tempo_prob_dist=norm(loc=89, scale=20), swing_prob=0.45, affinity=2),
    Descriptor(text="expertly arranged, catchy, and explosive", tempo_prob_dist=norm(loc=120, scale=30), swing_prob=0.5, affinity=3),
    Descriptor(text="middle-school slow-dance number", tempo_prob_dist=norm(loc=89, scale=10), swing_prob=0.2, affinity=1),
    Descriptor(text="welcome surprise", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="unabashedly disco, defrosting cryogenically frozen 70s strings", tempo_prob_dist=norm(loc=124, scale=8), swing_prob=0.03, affinity=2),
    Descriptor(text="breathy way of singing", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="a blur of quirked-up consonants", tempo_prob_dist=None, swing_prob=0.4, affinity=5),
    Descriptor(text="a freefall into impermanence", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="pulling back at the moment when it could strike hot", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="slicker than Sly and the Family Stone", tempo_prob_dist=norm(loc=118, scale=12), swing_prob=0.5, affinity=4),
    Descriptor(text="induces a mindset", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="restless mind telling itself to relax", tempo_prob_dist=None, swing_prob=0.4, affinity=3),
    Descriptor(text="crafted out of battering drums and cathartic lifts", tempo_prob_dist=None, swing_prob=0.5, affinity=3),
    Descriptor(text="wonderfully tragic story", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="spirit of brotherhood", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="a mashed-out confessional", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="twinkling riffs", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="a song that's both a celebration and a lament", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="thrilled to be alive", tempo_prob_dist=norm(loc=128, scale=27), swing_prob=0.5, affinity=2),
    Descriptor(text="subdued hum with a quaint production", tempo_prob_dist=None, swing_prob=0.2, affinity=2),
    Descriptor(text="more air in these sounds, more spontaneity, more dynamics", tempo_prob_dist=None, swing_prob=0.5, affinity=2),
    Descriptor(text="a woozy atmosphere", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="racing to contain its ambitions", tempo_prob_dist=norm(loc=143, scale=30), swing_prob=0.4, affinity=1),
    Descriptor(text="hiss of wind and some vague background chatter—the sounds of the everyday", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="a sound that's distinctly innate and closer to the ear", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="yearning for the return", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="solid rather than exhilarating", tempo_prob_dist=norm(loc=103, scale=15), swing_prob=0.3, affinity=1),
    Descriptor(text="expands the universe rather than contract it", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="begging for deliverance", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="keys/synths loom like cold skyscrapers in a stylized dystopia", tempo_prob_dist=norm(loc=110, scale=20), swing_prob=0.35, affinity=1),
    Descriptor(text="could have only come from an old master playfully grappling with the tools of our uncanny present moment", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="surrealistic choices that typify the record's sense of humor and insistence on finding joy and ecstasy", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="musically scattered and lyrically opaque", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="makes me want to dance and boogie and laugh", tempo_prob_dist=norm(loc=120, scale=15), swing_prob=0.55, affinity=4),
    Descriptor(text="a fluttering trifle that's nonetheless a powerful hit of straight pathos", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="quirky, political, thoughtful, weird—and sometimes drunk", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="pumping out juicy grooves galore underneath a glitzy flare", tempo_prob_dist=norm(loc=110, scale=25), swing_prob=0.5, affinity=1),
    Descriptor(text="absorbs the fanciful logic of fairy tales and deploys kooky, seemingly made-up phrases", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="feels bathed in the glow of a long sundown", tempo_prob_dist=norm(loc=94, scale=20), swing_prob=0.3, affinity=2),
    Descriptor(text="an energy that positively crackles", tempo_prob_dist=norm(loc=135, scale=40), swing_prob=0.5, affinity=1),
    Descriptor(text="bristles with intellectual awareness", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="an ecstatic fusion of alt-rock and R&B", tempo_prob_dist=norm(loc=105, scale=25), swing_prob=0.5, affinity=1),
    Descriptor(text="floats along like a dream", tempo_prob_dist=norm(loc=110, scale=35), swing_prob=0.5, affinity=1),
    Descriptor(text="sly, jubilant sound", tempo_prob_dist=norm(loc=110, scale=15), swing_prob=0.5, affinity=3),
    Descriptor(text="a liquid perfume that made you feel slightly sick", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="lithe acoustic throwaway", tempo_prob_dist=norm(loc=110, scale=35), swing_prob=0.3, affinity=1),
    Descriptor(text="builds toward a gospel-like peak", tempo_prob_dist=norm(loc=96, scale=20), swing_prob=0.6, affinity=1),
    Descriptor(text="the most personal admission on the album", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="delicate but resonant timbre", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="engineered to flash against your eyelids", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="a simultaneously hokey and bombastic feel", tempo_prob_dist=norm(loc=114, scale=20), swing_prob=0.5, affinity=2),
    Descriptor(text="buttoned-up and breezy", tempo_prob_dist=norm(loc=114, scale=19), swing_prob=0.54, affinity=3),
    Descriptor(text="advancing like a battalion", tempo_prob_dist=norm(loc=115, scale=25), swing_prob=0.4, affinity=1),
    Descriptor(text="brighter, tighter, and weirder than proclaimed", tempo_prob_dist=norm(loc=119, scale=40), swing_prob=0.5, affinity=1),
    Descriptor(text="inflected them with frenetic cool", tempo_prob_dist=norm(loc=120, scale=28), swing_prob=0.5, affinity=2),
    Descriptor(text="a moment that stops the clock cold", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="characterized by the gradual accumulation and subtraction of melodic and rhythmic gestures", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="encapsulates a sweetness and sense of humour", tempo_prob_dist=norm(loc=120, scale=28), swing_prob=0.55, affinity=1),
    Descriptor(text="honeyed voice", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="wholly cathartic", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="built around a bad bit of slang", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="a groove that pokes you in the side", tempo_prob_dist=norm(loc=110, scale=20), swing_prob=0.5, affinity=3),
    Descriptor(text="rinky-dink", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="the great sigh after a long holding of breath", tempo_prob_dist=None, swing_prob=0.3, affinity=9),
    Descriptor(text="a sanctuary in which all sorts of transfigurations become possible", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="sounded overlong, but still moving forward", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="listening with friends on the basement couch", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="nifty twinkling underneath", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="perilous chandelier at the center", tempo_prob_dist=None, swing_prob=0.35, affinity=1),
    Descriptor(text="delights in a carefree, mosaic approach", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="its strength lies in its more vulnerable moments", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="rides a sparser R&B groove", tempo_prob_dist=norm(loc=89, scale=15), swing_prob=0.5, affinity=1),
    Descriptor(text="recontextualize virtually all music as street music", tempo_prob_dist=None, swing_prob=0.5, affinity=2),
    Descriptor(text="the tension mounting as the rubbery doppler bass lurches ever closer", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="combining the everyday music with ascendant sounds", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="conjuring brisk coolness and intense yearning alike", tempo_prob_dist=norm(loc=117, scale=28), swing_prob=0.5, affinity=3),
    Descriptor(text="sunny, celebratory music", tempo_prob_dist=norm(loc=120, scale=20), swing_prob=0.6, affinity=2),
    Descriptor(text="drifting", tempo_prob_dist=norm(loc=90, scale=17), swing_prob=0.6, affinity=2),
    Descriptor(text="rise above a heavy-headed murmur into a smooth, often passionate classic-soul lead", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="world of their own invention", tempo_prob_dist=None, swing_prob=0.4, affinity=4),
    Descriptor(text="makes living paycheck to paycheck feel like a dream", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="basks in its heat", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="a riff reaching almost ecclesiastical joy", tempo_prob_dist=norm(loc=100, scale=20), swing_prob=0.5, affinity=4),
    Descriptor(text="silences crackled with old life", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="voice replicates itself until they are a chorus of supplicants", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="frat boy spin on Elvis Costello", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="continuation of a Springsteen-ian theme", tempo_prob_dist=norm(loc=107, scale=20), swing_prob=0.5, affinity=2),
    Descriptor(text="snoozy charm", tempo_prob_dist=norm(loc=83, scale=14), swing_prob=0.3, affinity=1),
    Descriptor(text="satirical and beautifully absurd", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="juvenile jazzbo", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="captured with a warm affection", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="wealth and privilege didn't necessarily guarantee a great life", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="carries an irresistible pulse", tempo_prob_dist=norm(loc=115, scale=18), swing_prob=0.5, affinity=1),
    Descriptor(text="infused with an unwavering sense of optimism", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="treads an enchanting path", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="full of twists and turns", tempo_prob_dist=None, swing_prob=0.5, affinity=1),
    Descriptor(text="roaring with jet engine propulsion", tempo_prob_dist=norm(loc=130, scale=25), swing_prob=0.4, affinity=1),
    Descriptor(text="aural equivalent of late-night channel surfing", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="juxtapositions of natural sounds to processed ones", tempo_prob_dist=None, swing_prob=0.4, affinity=1),
    Descriptor(text="unabashedly cartoonish", tempo_prob_dist=None, swing_prob=0.5, affinity=2),
    Descriptor(text="showcases the playful side of funk", tempo_prob_dist=norm(loc=100, scale=20), swing_prob=0.6, affinity=1),
    Descriptor(text="exhausted by big questions, consigned to tiny reminders", tempo_prob_dist=None, swing_prob=0.3, affinity=10),
    Descriptor(text="resounds with the fullness, somehow, of a life lived", tempo_prob_dist=None, swing_prob=0.4, affinity=9),
    Descriptor(text="chords that slip sideways, tumbling into one another", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="comfortable heading for the dancefloor", tempo_prob_dist=norm(loc=126, scale=18), swing_prob=0.5, affinity=1),
    Descriptor(text="minimal session reading like a songwriter's demo and vocal audition", tempo_prob_dist=None, swing_prob=0.3, affinity=1),
    Descriptor(text="if this record was in your house in 1968, you were no doubt listening to it all day long, tears of joy streaming down your face", tempo_prob_dist=norm(loc=108, scale=20), swing_prob=0.3, affinity=1),
    Descriptor(text="squirrelly sense of humor and a barely veiled obsession with death", tempo_prob_dist=norm(loc=130, scale=25), swing_prob=0.2, affinity=1),
    Descriptor(text="economical writing with chipper, pattering melody", tempo_prob_dist=norm(loc=123, scale=26), swing_prob=0.5, affinity=1),
    Descriptor(text="more inventive and sprightly", tempo_prob_dist=norm(loc=125, scale=20), swing_prob=0.35, affinity=2),
    Descriptor(text="bitter, grizzled, refreshing", tempo_prob_dist=norm(loc=99, scale=20), swing_prob=0.3, affinity=1),
    Descriptor(text="injecting new verve into the songwriting", tempo_prob_dist=norm(loc=115, scale=20), swing_prob=0.4, affinity=1),
    Descriptor(text="The one song Jack Stratton wishes he wrote", tempo_prob_dist=None, swing_prob=None, affinity=2),
    Descriptor(text="proportionally life-giving, indulgent, and periodically goofy", tempo_prob_dist=norm(loc=108, scale=20), swing_prob=0.4, affinity=1),  # ++
    Descriptor(text="deeply antagonistic with a vestigial bite", tempo_prob_dist=norm(loc=120, scale=25), swing_prob=0.2, affinity=1),
    Descriptor(text="everything denatures and melts", tempo_prob_dist=None, swing_prob=None, affinity=1),
    Descriptor(text="syncretic funk", tempo_prob_dist=norm(loc=114, scale=20), swing_prob=0.6, affinity=1),
    Descriptor(text="a crystalline duet", tempo_prob_dist=norm(loc=72, scale=10), swing_prob=0.1, affinity=1),
    Descriptor(text="bathing in misty sunshine", tempo_prob_dist=norm(loc=85, scale=15), swing_prob=0.3, affinity=2),
    Descriptor(text="melancholy, with lilting ambience", tempo_prob_dist=norm(loc=87, scale=20), swing_prob=0.2, affinity=1),
    Descriptor(text="gently twisted perspective", tempo_prob_dist=None, swing_prob=None, affinity=1),
    Descriptor(text="roams from bobbing indie folk to crashing rock reminiscent of St. Vincent", tempo_prob_dist=None, swing_prob=None, affinity=1),
    Descriptor(text="in marginally better spirits", tempo_prob_dist=None, swing_prob=0.3, affinity=9),
    Descriptor(text="a beautiful, alien life form streaking past our sight", tempo_prob_dist=None, swing_prob=None, affinity=9),
    Descriptor(text="feels like you're being preached at while listening", tempo_prob_dist=None, swing_prob=None, affinity=1),
    Descriptor(text="the savviest and most omnivorous pop", tempo_prob_dist=norm(loc=115, scale=25), swing_prob=0.4, affinity=1),
    Descriptor(text="harmonies that linger like a sunbeam", tempo_prob_dist=None, swing_prob=0.2, affinity=5),
    Descriptor(text="manic, weird, and provocatively cross-cultural", tempo_prob_dist=norm(loc=128, scale=30), swing_prob=0.1, affinity=1),
    Descriptor(text="swerving drastically, flopping catastrophically and still very happy", tempo_prob_dist=norm(loc=119, scale=31), swing_prob=0.25, affinity=2),
    Descriptor(text="a crisp funky", tempo_prob_dist=norm(loc=112, scale=20), swing_prob=0.6, affinity=1),
    Descriptor(text="goofy and red-eyed", tempo_prob_dist=None, swing_prob=0.4, affinity=2),
    Descriptor(text="offers a worthwhile escape with understated grace", tempo_prob_dist=None, swing_prob=0.2, affinity=2),
    Descriptor(text="anxiously placating a tense situation", tempo_prob_dist=norm(loc=118, scale=26), swing_prob=0.35, affinity=1),
    Descriptor(text="talky pastoral funk song", tempo_prob_dist=norm(loc=105, scale=18), swing_prob=0.5, affinity=3),
    Descriptor(text="more sensual revamp lightening up the mood", tempo_prob_dist=norm(loc=100, scale=20), swing_prob=0.45, affinity=1),
    Descriptor(text="taking a leap forward into emotional directness", tempo_prob_dist=None, swing_prob=None, affinity=2),
    Descriptor(text="...square dance, opera, rock, it's like I don't even know what to say about this thing.", tempo_prob_dist=None, swing_prob=None, affinity=1),
    Descriptor(text="a love song of the highest order, and there's nothing ironic about it", tempo_prob_dist=None, swing_prob=None, affinity=1),
    Descriptor(text="emotive sequence of chords gathers sweet backing harmonies", tempo_prob_dist=None, swing_prob=0.25, affinity=2),
    Descriptor(text="perfect contrast to the rainy weather outside", tempo_prob_dist=None, swing_prob=0.48, affinity=1),
    Descriptor(text="conjuring the myth of ordinary people", tempo_prob_dist=None, swing_prob=None, affinity=8),
    Descriptor(text="concerns itself with the aimlessness and absurdity of everyday life", tempo_prob_dist=norm(loc=100, scale=25), swing_prob=0.3, affinity=1),
    Descriptor(text="appealingly laid-back", tempo_prob_dist=norm(loc=88, scale=19), swing_prob=0.3, affinity=1),
    Descriptor(text="delectable and dejected in one gorgeously vulnerable package", tempo_prob_dist=None, swing_prob=0.2, affinity=2),
    Descriptor(text="a most exhilarating evocation of youth", tempo_prob_dist=norm(loc=130, scale=25), swing_prob=0.4, affinity=2),
    Descriptor(text="admitting the weight of lightness, that things are okay", tempo_prob_dist=None, swing_prob=0.3, affinity=5),
    Descriptor(text="spacy, Daft Punk-indebted undulation", tempo_prob_dist=norm(loc=115, scale=20), swing_prob=0.1, affinity=1),
    Descriptor(text="treats you lovingly", tempo_prob_dist=norm(loc=80, scale=10), swing_prob=0.25, affinity=1),
]
