INTERESTING_LYRICAL_IDEAS = [
    "engaging in an academic pursuit (studying/research) with a love interest",
    "3rd person description of the chemistry (good or bad) between two people",
    "the rift between ego and reality through a comparison to possessions (e.g. 'He owns a truck, but, but he drives a Saab')",
    "preocupation with money",
    "a reference/comparison to a Greek myth",
    "a reference/comparison to Shakespeare",
    "something that culminates in the production of sweat",
    "something you want to say, but can't",
    "what's the that could happen/worst case scenario",
    "a nice moment at either an airport or a train station",
    "saying thank you ironically (E.g. thanks for nothing)",
    "needing time to think",
    "a force of nature (e.g. a hurricane, tornado, tsunami, volcano, flood, drought, blizzard, wildfire, earthquake, landslide, meteor, comet, solar flare, supernova, black hole, gamma ray burst, solar eclipse...)",
    "surviving an apocolypse",
    "an ode to a city",
    "the humanity of a robot",
    "being unbreakable, untamable, and unshakeable",
    "hanging on, (i.e. 'stayin' alive') and still being awesome",
    "who killed the _________?",
    "a heist of a valuable object",
    "just a statistic",
    "having momentum",
    "somethings that's a blessing in disguise",
    "requesting that someone pull themselves together"
    "getting bent out of shape (upset)",
    "your guess is as good as mine",
    "method to a certain madness",
    "cutting the mustard (being good enough)",
    "requesting someone to stop their nonsense/shenanigans/monkey business",
    "you spoil all the fun (you're a wet blanket)",
    "bursting at the seams with _________",
    "bury me with my _________",
    "walking through a maze, seeking an exit or an answer",
    "when you left for mars, did you remember to trim your eyebrows for telescopes in backyards?",
    "the mysterious case of losing your care for something",
    "two friends jamming (metaphorically, i.e. having some good chemistry) together"
    "a kamikaze lover",
    "the sentiment escapes your tongue",
    "the relationship between the guru/sensei/mentor and the student",
    "i'm not avoiding you, I'm just _________",
    "a state trooper",
    "an amazing marine biologist",
    "actually, I'm specifically meaning you",
    "running on _________",
    "anything can happen (you never know)",
    "a rite of passage",
    "an athlete (strenght? long distance?)",
    "long distance",
    "the renewal of a morning where you wake up with an ephemeral sense of _______ (hope? purpose? clarity?)",
    "voices in your head",
    "building a bridge across a delta that represents _________",
    "still ________ after all this time",
    "when you're with _______, you (inevitably) ________",
    "not following the prescribed ________ (dancing/acting with an organic spontaneity)",
    "look ahead, not behind -- trust in the (forward) path",
    "you twist me up (with your words)... I think I can let it rest, but you are much to clever (a la Sweet Talkin Woman)",
    "what did I do before you? (I must have been quite the sight)",
    "take us home (finish the evening with the time-tested conduit - a song, a person, an activity, a dance)"
    "you vivify me (things become more vivid, etc.)"
    "wishing someone misfortune",
    "the winningest (most fortunate?) losers",
    "you think we're racing, but I'm on my victory lap",
    "keep an open mind (I've got something great to show you, despite the the onboarding process to the concept)",
    "do your thing (not someone elses)",
    "this is my special place - for dancing, celebrating, communing with life/joy/friends (I'm sharing it with you)",
    "don't cry (I'm/they're not worth it)",
    "I may not be in fashion, but I'm always in style (transport you to the right time?)",
    "not being high social status, but being better",
    "we're strangers until we aren't (come get to know me)",
    "facing fears",
    "let me plead my case",
    "moonlight __________ (mystery, crime, romance, etc.)",
    "do you __________?",
    "no thank you (I'm not interested)",
    "blowing smoke (not being honest)",
    "playing it down",
    "don't shrug me off (undervalue me)",
    "there's no smoke without fire, no _________ without _________...",
    "coughing up something (just admit it!)",
    "adding fuel to the fire",
    "get of my back (stop bothering me)",
    "missing a (the) boat (getting left behind)",
    "like hotcakes",
    "a situation that is too ambiguous, too amorphous"
    "the first time I saw in a/the _______ (ocean, mirror, your element, a vulnerable position etc.)",
    "being highly industrial or productive",
    "a highway for _________ (anything related to a highway)",
    "a bee in a bonnet (the thing that is stuck in someone's head)",
    "getting a kick out of something (getting your kicks)... i.e. 'where do you get your kicks? what makes you tick?'",
    "tell me ______, I'm all ears",
    "rubbing salt on a wound (making things worse)",
    "being second to none (the best)",
    "heaven knows (how I feel, etc.)",
    "not seeing eye to eye",
    "going at a snail's pace",
    "storm in a teacup (great commotion over a trivial matter)",
    "icing on the cake of disappointment",
    "two is better than one, let's collaborate",
    "paint the town red (celebrate wildly)",
    "a place where you feel totally comfortable (with an old friend, at the watering hole with your buddies, etc.)",
    "save your breath",
]

# Maybe useful?: https://www.hooktheory.com/

# HARMONIC_PROMPTS = [
#     "I | IIm | VIm | ♭VII",  # kinda sad
#     "IIm | V | IV | ♭VII | IIm | V | ♭VII | I",  # inquisitive but with resolution, ballad-y
#     "I | IV | IIm | V | IIIm | VIm | ♭VII | IV",  # bittersweet triumph
#     "I | IV | ♭VII | IV",  # confused resolution
#     "I | I7 | VII | I7",  # staying alive verse
#     "I | I | I | V | IV | IV | IV | I"  # go your own way verse
#     " I | VI | IV | II"  # basic
#     "I | VIm | IV | V",  # basic
#     "I | ♭VII | IV",  # mixolydian cadence
# ]
